# version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    env_file:
      - .env
    logging:
      driver: none
  
  payload:
    container_name: payload
    # image: node:22-alpine
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    # working_dir: /home/node/app/
    # command: sh -c "pnpm install && pnpm dev"
    ports:
      - '3000:3000'
    env_file:
      - .env  
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo

volumes:
  data:
  node_modules:
