# version: '3'

services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb-dev
    ports:
      - '27017:27017'
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    volumes:
      - mongodb_data:/data/db
    environment:
    - GLIBC_TUNABLES=glibc.pthread.rseq=1
    env_file:
      - .env
    # logging:
    #   driver: none
    restart: unless-stopped
  
  payload:
    container_name: payload
    # image: node:22-alpine
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    # working_dir: /home/node/app/
    # command: sh -c "pnpm install && pnpm dev"
    ports:
      - '3000:3000'
    env_file:
      - .env  
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb

volumes:
  mongodb_data:
  node_modules:
